<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Wallet;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class LegacyUserSeeder extends Seeder
{
    /**
     * Imported from legacy KlassPay database.
     * Fields mapped: firstname+lastname→name, contact_info→phone,
     * type→is_admin, user_type(0=normal,1=agent)→user_type,
     * balance→wallet.balance, pin→transaction_pin (re-hashed).
     */
    public function run(): void
    {
        $users = [
            [
                'username'     => 'Admin',
                'name'         => 'Admin KlassPay',
                'email'        => 'info@klasspay.com.ng',
                'password'     => '$2y$10$y4isaLLzF8Uf.HO4ay1/s.JakKFajz6C894zR0SWlwCquubVOdGWa',
                'phone'        => '09031704109',
                'pin'          => '1234',
                'is_admin'     => true,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-07-27 06:23:09',
            ],
            [
                'username'     => 'adebcov17',
                'name'         => 'Adebisi Covenant',
                'email'        => 'adebisicovenant01@gmail.com',
                'password'     => '$2y$10$/NxSAVuPGK1BBQsQMqJqP.HktQc/BRlW9ZjSKZXbn3ZzE0JWMiC3u',
                'phone'        => '09031704108',
                'pin'          => '4559',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 976.00,
                'created_at'   => '2025-07-29 09:44:46',
            ],
            [
                'username'     => 'charago42',
                'name'         => 'Charles Agomuo',
                'email'        => 'agocharles@yahoo.com',
                'password'     => '$2y$10$7c5BtDxR/o/rMM5.52VyQ.lESTYX9Vbu82vtTmeoVttO3ncxhHYa.',
                'phone'        => '08066353617',
                'pin'          => '2352',
                'is_admin'     => false,
                'user_type'    => 'agent',
                'is_active'    => true,
                'balance'      => 3125.00,
                'created_at'   => '2025-07-31 06:55:18',
            ],
            [
                'username'     => 'dolcdol93',
                'name'         => 'Dolce Dolce',
                'email'        => 'testaaccurate234@gmail.com',
                'password'     => '$2y$10$ROP6cG3RVdSOar91SRPTNOgN33UEhE3.n0uYyT65dOQEf8R0S68DS',
                'phone'        => '09033918495',
                'pin'          => '1111',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-08-04 05:42:18',
            ],
            [
                'username'     => 'thadsam64',
                'name'         => 'Thaddeaus Samuel',
                'email'        => 'uniquecreativenotion@gmail.com',
                'password'     => '$2y$10$PehC0lDTh83.uIXikGJcC.zXuv3aSA1Lldfth0k6MvBXNgRWqPbGK',
                'phone'        => '08131993400',
                'pin'          => '1107',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-15 08:28:31',
            ],
            [
                'username'     => 'chriade83',
                'name'         => 'Christopher Ade',
                'email'        => 'adeboye737@gmail.com',
                'password'     => '$2y$10$IwyZs0Po4/GELjcVpNcyu.ZFmRyKgytapFaTDqpktJIaBL5shzzfi',
                'phone'        => '07034609083',
                'pin'          => '1234',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-15 19:45:30',
            ],
            [
                'username'     => 'odelkeh74',
                'name'         => 'Odeleye Kehinde',
                'email'        => 'kehindeodeleye70@gmail.com',
                'password'     => '$2y$10$9yQ8V0mPHOIicD4b.wVGOeOEHebjiiIfNh7/qMT1Qt38wK1ZKKiSG',
                'phone'        => '09155788954',
                'pin'          => '2060',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-16 08:23:06',
            ],
            [
                'username'     => 'ibraabu82',
                'name'         => 'Ibrahim Abubakar',
                'email'        => 'ibsonyabour1@gmail.com',
                'password'     => '$2y$10$TqfiMELIkznJuKkCV9BMveNGQQ873QLWyp6FxR1ZJ2G8AOsVWjc9u',
                'phone'        => '07046173094',
                'pin'          => '0814',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-16 14:57:20',
            ],
            [
                'username'     => 'shenimo64',
                'name'         => 'Sheneni Imoh',
                'email'        => 'sheneniimoh2020@gmail.com',
                'password'     => '$2y$10$JbQSHBT9Y.EgO/FS/8zO/OmuRK/wlJVRwd6xxQzt.Drfa3Suimyg6',
                'phone'        => '08077935264',
                'pin'          => '2025',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-16 15:53:34',
            ],
            [
                'username'     => 'anifdam68',
                'name'         => 'Anifowoshe Damilare',
                'email'        => 'dcempires565@gmail.com',
                'password'     => '$2y$10$/10mRrfB/dTxg4AiyfwUb.7DY5pmn9Mo.bD.YGbfpMbhsFp.FrElq',
                'phone'        => '09156319856',
                'pin'          => '4554',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-16 18:43:11',
            ],
            [
                'username'     => 'amodabr37',
                'name'         => 'Amodu Abraham',
                'email'        => 'abrahamamodu30@gmail.com',
                'password'     => '$2y$10$BRXSohP2xCVqPVPYPgMClezaZRWMDcARXnCvmV2IKH46CX9Wkn/MW',
                'phone'        => '07062904603',
                'pin'          => '1111',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-16 19:23:48',
            ],
            [
                'username'     => 'maryabu36',
                'name'         => 'Maryam Abubakar',
                'email'        => 'evans400k@gmail.com',
                'password'     => '$2y$10$HyPBMvXhuKFP5./SEpWlweoA/7bLFd5FWR.osCqe1iRJ.pAihCiB6',
                'phone'        => '09154764642',
                'pin'          => '6474',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 500.00,
                'created_at'   => '2025-10-16 21:22:20',
            ],
            [
                'username'     => 'midealu28',
                'name'         => 'Mide Alu',
                'email'        => 'hindatup@gmail.com',
                'password'     => '$2y$10$J4UwXOSc7Y4VLC2paMpCoODnYgHua4WH0wpahbScLplwJXYvscGBq',
                'phone'        => '08138053919',
                'pin'          => '2222',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 302.00,
                'created_at'   => '2025-10-17 02:00:20',
            ],
            [
                'username'     => 'keneuja39',
                'name'         => 'Kenedy Ujah',
                'email'        => 'jude7878998@gmail.com',
                'password'     => '$2y$10$I7RHzheoHRx9N.9xdTlF.Ow51MCC3TsJ3MKx7C4vMr4QFA85xn05e',
                'phone'        => '09077672409',
                'pin'          => '5869',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-17 10:07:50',
            ],
            [
                'username'     => 'ikedjoh44',
                'name'         => 'Ikedi Johnpaul',
                'email'        => 'cruztatana8@gmail.com',
                'password'     => '$2y$10$s3jgEW8E9gyhvkOoY8t5aOwKSY1g.SywWBdjFa8zMRRFN65/KPlkS',
                'phone'        => '09033679790',
                'pin'          => '8000',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-17 11:42:45',
            ],
            [
                'username'     => 'sunnale64',
                'name'         => 'Sunnie Aleghe',
                'email'        => 'sunniealeghe@gmail.com',
                'password'     => '$2y$10$ns1sYU1gm5TaqOEeRaxx7Ok9k/whOMYj2RKsdKYbG9H8nQfVY1otG',
                'phone'        => '08181000013',
                'pin'          => '1965',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 29785.00,
                'created_at'   => '2025-10-17 15:14:40',
            ],
            [
                'username'     => 'victjos36',
                'name'         => 'Victor Joshua',
                'email'        => 'ilemonavictor1@gmail.com',
                'password'     => '$2y$10$K4sg6EkB7jLdtULHd/8Cg.6koWmU3zweqhRrZNpNA.oJVDulQpNoG',
                'phone'        => '09012507723',
                'pin'          => '1990',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-17 16:32:30',
            ],
            [
                'username'     => 'kehiade55',
                'name'         => 'Kehinde Adesola',
                'email'        => 'tell5sign@gmail.com',
                'password'     => '$2y$10$Us2ubDLw80w6ZHVGeEsA9.ngz8TG0n6n.I4YKGbbrVAJ.0ykl/s16',
                'phone'        => '07088670741',
                'pin'          => '2222',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-17 19:18:37',
            ],
            [
                'username'     => 'adamabd27',
                'name'         => 'Adamu Abdullahi',
                'email'        => 'sunusinafiu030@gmail.com',
                'password'     => '$2y$10$.duibRKoVLvKdwliDxYqYuPM8sxJG9J3lh/ljk5e5nZB3Pu3hhzIa',
                'phone'        => '09033627699',
                'pin'          => '2222',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 2.03,
                'created_at'   => '2025-10-17 20:24:35',
            ],
            [
                'username'     => 'ademroq88',
                'name'         => 'Ademola Roqeeb',
                'email'        => 'ademolaroqeebk@gmail.com',
                'password'     => '$2y$10$H2UzaBTG05eCv/a2jTvvaOMBf2HOJpj9XYsUnEIFCuCj2wgoPfmf6',
                'phone'        => '09139067936',
                'pin'          => '2007',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-17 22:33:58',
            ],
            [
                'username'     => 'aududog40',
                'name'         => 'Audu Dogo',
                'email'        => 'dogoaudu9@gmail.com',
                'password'     => '$2y$10$y4Kog8UWEX9csQpZ7TG4xOkPLz09cozL9a5XMbW69Lz50oGz9Y/lW',
                'phone'        => '08034881971',
                'pin'          => '2023',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-18 04:30:39',
            ],
            [
                'username'     => 'joycmay62',
                'name'         => 'Joyce Maye',
                'email'        => 'joycemayelizzyg@yahoo.com',
                'password'     => '$2y$10$x8QdkDiU.Xze3g4nmzWDsesDbFySlUEKvXtX51hRtX6yKd8WNKzre',
                'phone'        => '07055965142',
                'pin'          => '2222',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-18 10:57:14',
            ],
            [
                'username'     => 'musaauw55',
                'name'         => 'Musa Auwal',
                'email'        => 'verattiveratti51@gmail.com',
                'password'     => '$2y$10$3kZY7nQKp//BrvR9vHrHKeWNNiffvhEdovLwkn95cKYw5FvZKmM4W',
                'phone'        => '08085501399',
                'pin'          => '2255',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-18 16:15:44',
            ],
            [
                'username'     => 'abduuma10',
                'name'         => 'Abdullahi Umar Haddad',
                'email'        => 'abdullahiumarhaddad53@gmail.com',
                'password'     => '$2y$10$gWh.KLsxUHXGehOIVYUnU.M065lDJDOPhbPjz5cSFlMwDSnQ70Me2',
                'phone'        => '09163719653',
                'pin'          => '9943',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-18 18:30:33',
            ],
            [
                'username'     => 'erialou10',
                'name'         => 'Eriakha Louis',
                'email'        => 'blacksnow57@gmail.com',
                'password'     => '$2y$10$H1rK0tqTueIIDcqTHE8KduabDLI1SicBaIKDl0Vvh.jFQh7ouP8Dy',
                'phone'        => '08099445101',
                'pin'          => '1984',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 5.95,
                'created_at'   => '2025-10-18 19:32:32',
            ],
            [
                'username'     => 'ifeaegw59',
                'name'         => 'Ifeanyi Egwim',
                'email'        => 'ifeanyiken.ie52@gmail.com',
                'password'     => '$2y$10$elNT3RxZa.BL6chvIgBftuGbwu9bPtAkIULihjtwuldjFAbqa3hNe',
                'phone'        => '09035663657',
                'pin'          => '3939',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-19 08:24:33',
            ],
            [
                'username'     => 'godwima31',
                'name'         => 'Godwin Imakhai',
                'email'        => 'imoesichambers@gmail.com',
                'password'     => '$2y$10$BWWGThcHvoH15vfplDl4queO4Ag9R7x2R2PEetmAVG5Z/LM.L6pUK',
                'phone'        => '08054145214',
                'pin'          => '0767',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-19 09:40:50',
            ],
            [
                'username'     => 'austakh16',
                'name'         => 'Austin Akhabue',
                'email'        => 'austinakhabue00@gmail.com',
                'password'     => '$2y$10$8njdrcGT23k1B1NJSI0DD.ceA5M1zcNWflUcmgygKYzefIDX0ZmaC',
                'phone'        => '08023544546',
                'pin'          => '1234',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-19 09:49:20',
            ],
            [
                'username'     => 'lazaale70',
                'name'         => 'Lazarus Aleghe',
                'email'        => 'lazarusaleghe@gmail.com',
                'password'     => '$2y$10$anzmu3Zi7mpv0KurUAUmdO73ybcWAByHWLiet2ioWkeMWX8P.xF4K',
                'phone'        => '08038368198',
                'pin'          => '1984',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-19 18:44:15',
            ],
            [
                'username'     => 'habipop44',
                'name'         => 'Habib Popoola',
                'email'        => 'popularlowz@gmail.com',
                'password'     => '$2y$10$xuotM0deLgWBnrihO2Q34O9sj/.4hyUq/e8dNH/Gmpr/PjCq1ULGO',
                'phone'        => '08106052144',
                'pin'          => '3680',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-22 20:48:03',
            ],
            [
                'username'     => 'horlmhi34',
                'name'         => 'Horlar Mhi',
                'email'        => 'horlarewajuadam102@gmail.com',
                'password'     => '$2y$10$ZQbQS2mlSSTtZiJXDlYjR.3GwSwPh7Zl77DkWGL3JRQXO0IGIjMM2',
                'phone'        => '08134446780',
                'pin'          => '2244',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-10-24 19:47:37',
            ],
            [
                'username'     => 'obiondu20',
                'name'         => 'Obioma Ndubuisi',
                'email'        => 'linkobi@yahoo.com',
                'password'     => '$2y$10$sJLzCSjvwAf1tobVGUU/X.ofkYHbM0BnQ4I5ClL0hgz8lzY2UaERC',
                'phone'        => '08136836450',
                'pin'          => '4053',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 10.00,
                'created_at'   => '2025-10-24 20:12:36',
            ],
            [
                'username'     => 'adebbak74',
                'name'         => 'Adebayo Bakare',
                'email'        => 'mugupet868@gmail.com',
                'password'     => '$2y$10$oLmOn2xUtT3wG1yXD1oIee2CmWEgrcv23GFnsQqyuCNDeiSRxUjnm',
                'phone'        => '07063012438',
                'pin'          => '3322',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 5.00,
                'created_at'   => '2025-11-05 12:58:29',
            ],
            [
                'username'     => 'evidgif19',
                'name'         => 'Evidence Gift',
                'email'        => 'kingsleyg386@gmail.com',
                'password'     => '$2y$10$BsG.uolPeZUQ9QL8MDLg7unBGQG9NDqv1ErKjQJFP7GwLEOUeQzEW',
                'phone'        => '08066781528',
                'pin'          => '1234',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-11-18 10:57:27',
            ],
            [
                'username'     => 'jdndjgh92',
                'name'         => 'Jdndndhh Jghhgh',
                'email'        => 'prosperjasper002@gmail.com',
                'password'     => '$2y$10$2L4AJkc3cML1Pv5DuvSLY.62kUgkq/OqjuTvssnflfpXuT63pYl2i',
                'phone'        => '08088888888',
                'pin'          => '1234',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => false, // status=2 (suspended)
                'balance'      => 0.00,
                'created_at'   => '2025-12-10 16:55:38',
            ],
            [
                'username'     => 'vvvvvvv65',
                'name'         => 'Vvvvg Vvvvg',
                'email'        => 'prosperjasper003@gmail.com',
                'password'     => '$2y$10$hLQn/3mjt6fzIPu8b5R4AOdjIzngUvS1ip3CFfrCBDbHlVBOuBzlO',
                'phone'        => '08088888833',
                'pin'          => '1234',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => false, // status=2 (suspended)
                'balance'      => 0.00,
                'created_at'   => '2026-01-28 22:46:00',
            ],
            [
                'username'     => 'abasyus41',
                'name'         => 'Abass Yusuf',
                'email'        => 'nura001y@gmail.com',
                'password'     => '$2y$10$EcJR3AF6.a5f7Oq6zT20kerYQLr5jox.T2qZ8b/Yz.6JrZ/F7RboC',
                'phone'        => '08033454528',
                'pin'          => '2222',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-04-05 23:01:14',
            ],
        ];

        foreach ($users as $data) {
            $user = User::updateOrCreate(
                ['email' => $data['email']],
                [
                    'username'         => $data['username'],
                    'name'             => $data['name'],
                    'phone'            => $data['phone'],
                    'password'         => $data['password'],
                    'transaction_pin'  => Hash::make($data['pin']),
                    'is_admin'         => $data['is_admin'],
                    'user_type'        => $data['user_type'],
                    'is_active'        => $data['is_active'],
                    'referral_code'    => strtoupper(substr($data['username'], 0, 8)),
                    'email_verified_at' => now(), // treat all legacy users as verified
                    'created_at'       => $data['created_at'],
                    'updated_at'       => $data['created_at'],
                ]
            );

            // Create or update wallet with legacy balance
            Wallet::updateOrCreate(
                ['user_id' => $user->id],
                [
                    'balance'      => $data['balance'],
                    'total_funded' => $data['balance'], // treat opening balance as funded
                    'total_spent'  => 0,
                ]
            );
        }
    }
}
