<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Wallet;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class LegacyUserSeeder extends Seeder
{
    /**
     * Imported from legacy KlassPay database.
     * Fields mapped: firstname+lastname→name, contact_info→phone,
     * type→is_admin, user_type(0=normal,1=agent)→user_type,
     * balance→wallet.balance, pin→transaction_pin (re-hashed).
     */
    public function run(): void
    {
        $users = [
            [
                'username'     => 'dolcdol93',
                'name'         => 'dolce dolce',
                'email'        => 'testaaccurate234@gmail.com',
                'password'     => '$2y$10$ROP6cG3RVdSOar91SRPTNOgN33UEhE3.n0uYyT65dOQEf8R0S68DS',
                'phone'        => '09033918495',
                'pin'          => '1111',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-08-04 05:42:18',
            ],
            [
                'username'     => 'mohakha77',
                'name'         => 'Mohammed Khalid',
                'email'        => 'elkhaleedss@gmail.com',
                'password'     => '$2y$10$XTS.nVZi1Qd95wNofJdp8u/77.LXx754y.eVQje8xhxOYuIG8oPZ6',
                'phone'        => '08055576411',
                'pin'          => '4368',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-08-15 06:08:09',
            ],
            [
                'username'     => 'umaribr54',
                'name'         => 'Umar Ibrahim idris',
                'email'        => 'umaridrisibrahim@gmail.com',
                'password'     => '$2y$10$j/yhzoqfWZRit6Cp5lgFmOJfCXycjsehuLioBhZ3.CcKfMWNdzxOO',
                'phone'        => '08032031611',
                'pin'          => '5089',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-08-15 06:24:44',
            ],
            [
                'username'     => 'mohamus68',
                'name'         => 'Mohammed Mustapha',
                'email'        => 'mustaphahanayi@gmail.com',
                'password'     => '$2y$10$VJ7DprvFRZWqU7scVCpZN.wFb69mwQ0s1sS3FmVhBQkrcEpK2nymu',
                'phone'        => '07060878951',
                'pin'          => '2224',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-08-15 09:27:37',
            ],
            [
                'username'     => 'ismaidr28',
                'name'         => 'ismail idris',
                'email'        => 'ismail.idris555@gmail.com',
                'password'     => '$2y$10$4yezN.bfbsSWKwDswHfx2ucNjEnQ8hZuIyJ9bxM1eFDbnWymUd.yK',
                'phone'        => '09030090909',
                'pin'          => '9099',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 1000.00,
                'created_at'   => '2025-08-16 10:08:51',
            ],
            [
                'username'     => 'usmaibr82',
                'name'         => 'Usman Ibrahim',
                'email'        => 'nurainwater@gmail.com',
                'password'     => '$2y$10$hJ71JSmBN42Juz00t/Ry8OT6sScLW8v5ChIwe4hmfB.ehKVNBOaXm',
                'phone'        => '08026990436',
                'pin'          => '2699',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-08-20 16:31:30',
            ],
            [
                'username'     => 'musaibr76',
                'name'         => 'Musa Ibrahim',
                'email'        => 'musaibrahimidris27@gmail.com',
                'password'     => '$2y$10$TD8GeccPUzSqqMnEvvffXedhCOLeapdnM59lYExkqK8Flo3zifFtO',
                'phone'        => '09061222447',
                'pin'          => '6121',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-08-21 16:53:47',
            ],
            [
                'username'     => 'ahmeuma99',
                'name'         => 'Ahmed Umar',
                'email'        => 'ahmedumaribrahim230@gmail.com',
                'password'     => '$2y$10$kp6FLi4aYo7NhElxHrD6nebUCcGPazG.RJZtKF0kbuHm0PiFDikTq',
                'phone'        => '09129072704',
                'pin'          => '2010',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-08-21 17:00:11',
            ],
            [
                'username'     => 'ephrjam15',
                'name'         => 'Ephriam James',
                'email'        => 'ephraimjames19@gmail.com',
                'password'     => '$2y$10$HlgeXZvE/wpGzQF9s8.osO1vofRAJVWzV3HyHfX6IaUJqGICxKijq',
                'phone'        => '08058194000',
                'pin'          => '6371',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2025-09-17 11:56:58',
            ],
            [
                'username'     => 'ekoote64',
                'name'         => 'Eko Otene',
                'email'        => 'henryblinks123@gmail.com',
                'password'     => '$2y$10$S5ip/Jrop3xBRSZ/0uoF4OHMBuSzaAAGvYsvWKL75iQKYSY.MCPue',
                'phone'        => '08147973441',
                'pin'          => '8011',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 15.00,
                'created_at'   => '2025-09-17 11:59:03',
            ],
            [
                'username'     => 'danigim79',
                'name'         => 'Daniel Gimba',
                'email'        => 'danielgimba@gmail.com',
                'password'     => '$2y$10$jXgi0xRUIBt7nLx4dhzt.OPJux3glUghfgweFPDxF0nSg/YRjicWq',
                'phone'        => '08055579371',
                'pin'          => '5678',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 755.25,
                'created_at'   => '2026-01-24 07:01:37',
            ],
            [
                'username'     => 'babachi56',
                'name'         => 'Babagana Chiroma',
                'email'        => 'bgchiroma@gmail.com',
                'password'     => '$2y$10$EJuoCa/Ho8CMDALpTkauKOASbQmr6lYvIlSF2H1IHoAseTmzjLzOm',
                'phone'        => '08055576372',
                'pin'          => '3294',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 1000.00,
                'created_at'   => '2026-01-24 08:32:02',
            ],
            [
                'username'     => 'eneote62',
                'name'         => 'Ene Otene',
                'email'        => 'oteneenepauline@gmail.com',
                'password'     => '$2y$10$VC3FnDxw1MHBZAiZZKoda.LnECgyU/51euSooN79Jo2aviYcr/MVe',
                'phone'        => '08039671069',
                'pin'          => '1996',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-01-26 10:17:16',
            ],
            [
                'username'     => 'amancha10',
                'name'         => 'Amanda Charles',
                'email'        => 'missmandy600@gmail.com',
                'password'     => '$2y$10$WRQ0wOhrQvWgTUcD//noR.he2.J9kMlu7DdRo8u7bgyW61v6ym6hq',
                'phone'        => '08055573515',
                'pin'          => '1995',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-01-26 10:19:24',
            ],
            [
                'username'     => 'bukamoh88',
                'name'         => 'Bukar Mohammed',
                'email'        => 'bukarmohammed278@gmail.com',
                'password'     => '$2y$10$F6dS4vr0vmlsTOOwteF9nuHymLNuYphl4toFm7R0iGz21Q3Sjfhh6',
                'phone'        => '07050717575',
                'pin'          => '0705',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-01-27 08:06:12',
            ],
            [
                'username'     => 'vvvvvvv87',
                'name'         => 'Vvvvg Vvvvg',
                'email'        => 'prosperjasper002@gmail.com',
                'password'     => '$2y$10$jCPftf5jzNlTAgXWpe80Se2Sz8VPDkuqwWK7BKA0yyKs2SMaA2Gkm',
                'phone'        => '09037303701',
                'pin'          => '1234',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 100.00,
                'created_at'   => '2026-02-01 22:29:27',
            ],
            [
                'username'     => 'ocheote26',
                'name'         => 'Oche Otene',
                'email'        => 'oteneochecardinal@gmail.com',
                'password'     => '$2y$10$t6LlmiRDfrhndfq6OJtiTuqIoGNXfKWJRB2UCgcNXsHic59d4xT6e',
                'phone'        => '08055576412',
                'pin'          => '8011',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-02-17 06:38:39',
            ],
            [
                'username'     => 'kezitit95',
                'name'         => 'Keziah Titus',
                'email'        => 'keziahtitus112@gmail.com',
                'password'     => '$2y$10$DN7bnzUBDKqN9gzjvzfCOOBg.dGUavcb/08s5BuYnY1eMBZj5h4HO',
                'phone'        => '09155445588',
                'pin'          => '8011',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-02-17 07:02:43',
            ],
            [
                'username'     => 'awalgar28',
                'name'         => 'Awal Garba',
                'email'        => 'auwalgg@gmail.com',
                'password'     => '$2y$10$/6yZzPwuMmXKV5qEuaqaVenEnYWozeqfBRXeQairLlupnsDfSTcSO',
                'phone'        => '08023436551',
                'pin'          => '8011',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-02-17 07:07:52',
            ],
            [
                'username'     => 'eneote49',
                'name'         => 'Ene Otene',
                'email'        => 'enayiotene@gmail.com',
                'password'     => '$2y$10$iUiSagi7NEh10tNu1XWNwuq6LRPA7bdEVCW2jk26g6EpI5cMYpFCK',
                'phone'        => '08068712142',
                'pin'          => '8011',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-02-17 07:53:09',
            ],
            [
                'username'     => 'ritapri69',
                'name'         => 'Rita Priye',
                'email'        => 'Preyerita0@gmail.com',
                'password'     => '$2y$10$mGg2ShwhnAKK2AXKqm6c1eWm7ACjl0MY0Qa6XcJsJxSsQ2gBpvqpK',
                'phone'        => '08025154213',
                'pin'          => '8011',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-02-17 08:03:40',
            ],
            [
                'username'     => 'eugeaba67',
                'name'         => 'Eugene Abah',
                'email'        => 'eugeneabah@gmail.com',
                'password'     => '$2y$10$rywguVZQthnINjJmAzPsYu2zCD.3FWyyou7St.FmSV29FyDVNMrQC',
                'phone'        => '01254546791',
                'pin'          => '8011',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-02-19 21:00:06',
            ],
            [
                'username'     => 'sanizah59',
                'name'         => 'Sani Zaharaddini',
                'email'        => 'marypowell4190@gmail.com',
                'password'     => '$2y$10$pvENeZLiKmCCpPAjfL7r2.vw.Hd1R28PcOQXxxeeX1MhgmpEIdnMq',
                'phone'        => '07078536891',
                'pin'          => '2222',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-02-26 20:15:47',
            ],
            [
                'username'     => 'saliibr10',
                'name'         => 'Salisu Ibrahim',
                'email'        => 'salisuibrahim6611@gmail.com',
                'password'     => '$2y$10$LwQ/zbn5ACtvM1oCSQsTk.rnaylMQGgozyrJKtq5aznr3ZCZe7qjS',
                'phone'        => '09069346946',
                'pin'          => '6611',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-03-12 14:30:58',
            ],
            [
                'username'     => 'gambabd33',
                'name'         => 'Gambari Abdurasheed',
                'email'        => 'nura001y@gmail.com',
                'password'     => '$2y$10$9BPU4MSYc1Y4onpFxAExVeiopcxQtar9/RBPQZfIMZhJ7tsBNoWyq',
                'phone'        => '08036936936',
                'pin'          => '2222',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 26.08,
                'created_at'   => '2026-03-30 16:48:06',
            ],
            [
                'username'     => 'gambabd13',
                'name'         => 'Gambari Abdurasheed',
                'email'        => 'rolandgoodness707@gmail.com',
                'password'     => '$2y$10$WThomVk6fHsUGTovtPCMmu.Zp7fr5lDpJcZa6nUvWKm0qXsPnYN0q',
                'phone'        => '08036936925',
                'pin'          => '2222',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 144.92,
                'created_at'   => '2026-04-05 23:09:57',
            ],
            [
                'username'     => 'johnton95',
                'name'         => 'John Tonade',
                'email'        => 'tonadeoludare213@gmail.com',
                'password'     => '$2y$10$XNqr7Y/jLydurNvNsvAE8On0OaNlCXYeQ4SCDRXvbEwH8.JT8HzLm',
                'phone'        => '09046114146',
                'pin'          => '2222',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-04-09 17:30:23',
            ],
            [
                'username'     => 'omolasa77',
                'name'         => 'Omolayo Asagunla',
                'email'        => 'olamilekantobi100@gmail.com',
                'password'     => '$2y$10$2W0G06MUjrvWaTtjn9mtA.yC705lbrQLKBeY3PbyMDmCRhnWTQDA2',
                'phone'        => '08100091056',
                'pin'          => '2525',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-04-13 22:11:55',
            ],
            [
                'username'     => 'mustidr86',
                'name'         => 'Mustapha Idris',
                'email'        => 'mustaphalovesgugl@gmail.com',
                'password'     => '$2y$10$.xhuYfQes8p793ObRMH3V.cVE7hBfbfbAS1bptB0MgZ8eou46FaK.',
                'phone'        => '09061138536',
                'pin'          => '1212',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-06-13 03:36:03',
            ],
            [
                'username'     => 'jacoibr56',
                'name'         => 'Jacob Ibrahim',
                'email'        => 'jacobajidani@gmail.com',
                'password'     => '$2y$10$eNq1qW2jdr.wqafvr4qgReV6uCaxMkZA8buWHURojDnHuSZfmcjSm',
                'phone'        => '08075274444',
                'pin'          => '4146',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-06-21 08:21:58',
            ],
            [
                'username'     => 'ibrajam87',
                'name'         => 'Ibrahim Jamiu Adinoyi',
                'email'        => 'dinnoadonis1@gmail.com',
                'password'     => '$2y$10$8DaJOa0lxJy4uUDsd41qn.LVAUwPMNkWXDhGqcq6j0Zv9kae1xzpK',
                'phone'        => '08055576249',
                'pin'          => '3466',
                'is_admin'     => false,
                'user_type'    => 'normal',
                'is_active'    => true,
                'balance'      => 0.00,
                'created_at'   => '2026-06-30 20:44:10',
            ],
        ];

        foreach ($users as $data) {
            $user = User::updateOrCreate(
                ['email' => $data['email']],
                [
                    'username'         => $data['username'],
                    'name'             => $data['name'],
                    'phone'            => $data['phone'],
                    'password'         => $data['password'],
                    'transaction_pin'  => Hash::make($data['pin']),
                    'is_admin'         => $data['is_admin'],
                    'user_type'        => $data['user_type'],
                    'is_active'        => $data['is_active'],
                    'referral_code'    => strtoupper(substr($data['username'], 0, 8)),
                    'email_verified_at' => now(), // treat all legacy users as verified
                    'created_at'       => $data['created_at'],
                    'updated_at'       => $data['created_at'],
                ]
            );

            // Create or update wallet with legacy balance
            Wallet::updateOrCreate(
                ['user_id' => $user->id],
                [
                    'balance'      => $data['balance'],
                    'total_funded' => $data['balance'], // treat opening balance as funded
                    'total_spent'  => 0,
                ]
            );
        }
    }
}
