<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UserSettingsTest extends TestCase
{
    use RefreshDatabase;

    public function test_user_can_update_low_balance_notification_preference_via_post(): void
    {
        $user = User::factory()->create([
            'is_active' => true,
            'low_balance_notification' => false,
            'transaction_pin' => bcrypt('1234'),
            'phone_verified_at' => now(),
        ]);
        $user->wallet()->create(['balance' => 1000]);

        $this->actingAs($user);

        $response = $this->post(route('settings.notification'), [
            'low_balance_notification' => '1',
        ]);

        $response->assertRedirect(route('settings', ['tab' => 'profile']));
        $response->assertSessionHas('success', 'Notification preference saved.');

        $this->assertTrue($user->fresh()->low_balance_notification);
    }

    public function test_user_can_update_low_balance_notification_preference_via_put(): void
    {
        $user = User::factory()->create([
            'is_active' => true,
            'low_balance_notification' => false,
            'transaction_pin' => bcrypt('1234'),
            'phone_verified_at' => now(),
        ]);
        $user->wallet()->create(['balance' => 1000]);

        $this->actingAs($user);

        // Spoofing PUT request (as generated by Alpine/Laravel method spoofing inside the PUT form)
        $response = $this->put(route('settings.notification'), [
            'low_balance_notification' => '1',
        ]);

        $response->assertRedirect(route('settings', ['tab' => 'profile']));
        $response->assertSessionHas('success', 'Notification preference saved.');

        $this->assertTrue($user->fresh()->low_balance_notification);
    }

    public function test_user_can_upgrade_to_agent_with_sufficient_balance(): void
    {
        \App\Models\AppSetting::set('agent_upgrade_fee', 3000);

        $user = User::factory()->create([
            'is_active' => true,
            'user_type' => 'user',
            'transaction_pin' => bcrypt('1234'),
            'phone_verified_at' => now(),
        ]);
        $wallet = $user->wallet()->create(['balance' => 4000]);

        $this->actingAs($user);

        $response = $this->post(route('settings.upgrade-agent'));

        $response->assertRedirect(route('settings', ['tab' => 'profile']));
        $response->assertSessionHas('success', 'Congratulations! Your account has been upgraded to Agent.');

        $this->assertTrue($user->fresh()->isAgent());
        $this->assertEquals(1000, (float) $wallet->fresh()->balance);

        $this->assertDatabaseHas('wallet_transactions', [
            'user_id' => $user->id,
            'type' => 'debit',
            'amount' => 3000,
            'description' => 'Agent status upgrade fee',
        ]);
    }

    public function test_user_cannot_upgrade_to_agent_with_insufficient_balance(): void
    {
        \App\Models\AppSetting::set('agent_upgrade_fee', 5000);

        $user = User::factory()->create([
            'is_active' => true,
            'user_type' => 'user',
            'transaction_pin' => bcrypt('1234'),
            'phone_verified_at' => now(),
        ]);
        $wallet = $user->wallet()->create(['balance' => 3000]);

        $this->actingAs($user);

        $response = $this->post(route('settings.upgrade-agent'));

        $response->assertSessionHas('error', 'Insufficient wallet balance for agent upgrade.');
        $this->assertFalse($user->fresh()->isAgent());
        $this->assertEquals(3000, (float) $wallet->fresh()->balance);
    }

    public function test_admin_can_configure_agent_upgrade_fee(): void
    {
        $admin = User::factory()->create([
            'is_admin' => true,
            'is_active' => true,
        ]);

        $this->actingAs($admin);

        // Retrieve general settings
        $response = $this->get(route('admin.settings.general'));
        $response->assertStatus(200);
        $response->assertSee('Agent Upgrade Fee');

        // Update settings
        $response = $this->post(route('admin.settings.general.update'), [
            'site_name' => 'PayPulse Test',
            'agent_upgrade_fee' => '4500',
        ]);

        $response->assertSessionHas('success');
        $this->assertEquals('4500', \App\Models\AppSetting::get('agent_upgrade_fee'));
    }
}
